import {
    fa500px,
    faAccessibleIcon,
    faAccusoft,
    faAcquisitionsIncorporated,
    faAdn,
    faAdversal,
    faAffiliatetheme,
    faAirbnb,
    faAlgolia,
    faAlipay,
    faAmazon,
    faAmazonPay,
    faAmilia,
    faAndroid,
    faAngellist,
    faAngrycreative,
    faAngular,
    faAppStore,
    faAppStoreIos,
    faApper,
    faApple,
    faApplePay,
    faArtstation,
    faAsymmetrik,
    faAtlassian,
    faAudible,
    faAutoprefixer,
    faAvianex,
    faAviato,
    faAws,
    faBandcamp,
    faBattleNet,
    faBehance,
    faBehanceSquare,
    faBimobject,
    faBitbucket,
    faBitcoin,
    faBity,
    faBlackTie,
    faBlackberry,
    faBlogger,
    faBloggerB,
    faBluetooth,
    faBluetoothB,
    faBootstrap,
    faBtc,
    faBuffer,
    faBuromobelexperte,
    faBuyNLarge,
    faBuysellads,
    faCanadianMapleLeaf,
    faCcAmazonPay,
    faCcAmex,
    faCcApplePay,
    faCcDinersClub,
    faCcDiscover,
    faCcJcb,
    faCcMastercard,
    faCcPaypal,
    faCcStripe,
    faCcVisa,
    faCentercode,
    faCentos,
    faChrome,
    faChromecast,
    faCloudflare,
    faCloudscale,
    faCloudsmith,
    faCloudversify,
    faCodepen,
    faCodiepie,
    faConfluence,
    faConnectdevelop,
    faContao,
    faCottonBureau,
    faCpanel,
    faCreativeCommons,
    faCreativeCommonsBy,
    faCreativeCommonsNc,
    faCreativeCommonsNcEu,
    faCreativeCommonsNcJp,
    faCreativeCommonsNd,
    faCreativeCommonsPd,
    faCreativeCommonsPdAlt,
    faCreativeCommonsRemix,
    faCreativeCommonsSa,
    faCreativeCommonsSampling,
    faCreativeCommonsSamplingPlus,
    faCreativeCommonsShare,
    faCreativeCommonsZero,
    faCriticalRole,
    faCss3,
    faCss3Alt,
    faCuttlefish,
    faDAndD,
    faDAndDBeyond,
    faDailymotion,
    faDashcube,
    faDeezer,
    faDelicious,
    faDeploydog,
    faDeskpro,
    faDev,
    faDeviantart,
    faDhl,
    faDiaspora,
    faDigg,
    faDigitalOcean,
    faDiscord,
    faDiscourse,
    faDochub,
    faDocker,
    faDraft2digital,
    faDribbble,
    faDribbbleSquare,
    faDropbox,
    faDrupal,
    faDyalog,
    faEarlybirds,
    faEbay,
    faEdge,
    faEdgeLegacy,
    faElementor,
    faEllo,
    faEmber,
    faEmpire,
    faEnvira,
    faErlang,
    faEthereum,
    faEtsy,
    faEvernote,
    faExpeditedssl,
    faFacebook,
    faFacebookF,
    faFacebookMessenger,
    faFacebookSquare,
    faFantasyFlightGames,
    faFedex,
    faFedora,
    faFigma,
    faFirefox,
    faFirefoxBrowser,
    faFirstOrder,
    faFirstOrderAlt,
    faFirstdraft,
    faFlickr,
    faFlipboard,
    faFly,
    faFontAwesome,
    faFontAwesomeAlt,
    faFontAwesomeFlag,
    faFontAwesomeLogoFull,
    faFonticons,
    faFonticonsFi,
    faFortAwesome,
    faFortAwesomeAlt,
    faForumbee,
    faFoursquare,
    faFreeCodeCamp,
    faFreebsd,
    faFulcrum,
    faGalacticRepublic,
    faGalacticSenate,
    faGetPocket,
    faGg,
    faGgCircle,
    faGit,
    faGitAlt,
    faGitSquare,
    faGithub,
    faGithubAlt,
    faGithubSquare,
    faGitkraken,
    faGitlab,
    faGitter,
    faGlide,
    faGlideG,
    faGofore,
    faGoodreads,
    faGoodreadsG,
    faGoogle,
    faGoogleDrive,
    faGooglePay,
    faGooglePlay,
    faGooglePlus,
    faGooglePlusG,
    faGooglePlusSquare,
    faGoogleWallet,
    faGratipay,
    faGrav,
    faGripfire,
    faGrunt,
    faGuilded,
    faGulp,
    faHackerNews,
    faHackerNewsSquare,
    faHackerrank,
    faHips,
    faHireAHelper,
    faHive,
    faHooli,
    faHornbill,
    faHotjar,
    faHouzz,
    faHtml5,
    faHubspot,
    faIdeal,
    faImdb,
    faInnosoft,
    faInstagram,
    faInstagramSquare,
    faInstalod,
    faIntercom,
    faInternetExplorer,
    faInvision,
    faIoxhost,
    faItchIo,
    faItunes,
    faItunesNote,
    faJava,
    faJediOrder,
    faJenkins,
    faJira,
    faJoget,
    faJoomla,
    faJs,
    faJsSquare,
    faJsfiddle,
    faKaggle,
    faKeybase,
    faKeycdn,
    faKickstarter,
    faKickstarterK,
    faKorvue,
    faLaravel,
    faLastfm,
    faLastfmSquare,
    faLeanpub,
    faLess,
    faLine,
    faLinkedin,
    faLinkedinIn,
    faLinode,
    faLinux,
    faLyft,
    faMagento,
    faMailchimp,
    faMandalorian,
    faMarkdown,
    faMastodon,
    faMaxcdn,
    faMdb,
    faMedapps,
    faMedium,
    faMediumM,
    faMedrt,
    faMeetup,
    faMegaport,
    faMendeley,
    faMicroblog,
    faMicrosoft,
    faMix,
    faMixcloud,
    faMixer,
    faMizuni,
    faModx,
    faMonero,
    faNapster,
    faNeos,
    faNimblr,
    faNode,
    faNodeJs,
    faNpm,
    faNs8,
    faNutritionix,
    faOctopusDeploy,
    faOdnoklassniki,
    faOdnoklassnikiSquare,
    faOldRepublic,
    faOpencart,
    faOpenid,
    faOpera,
    faOptinMonster,
    faOrcid,
    faOsi,
    faPage4,
    faPagelines,
    faPalfed,
    faPatreon,
    faPaypal,
    faPennyArcade,
    faPerbyte,
    faPeriscope,
    faPhabricator,
    faPhoenixFramework,
    faPhoenixSquadron,
    faPhp,
    faPiedPiper,
    faPiedPiperAlt,
    faPiedPiperHat,
    faPiedPiperPp,
    faPiedPiperSquare,
    faPinterest,
    faPinterestP,
    faPinterestSquare,
    faPlaystation,
    faProductHunt,
    faPushed,
    faPython,
    faQq,
    faQuinscape,
    faQuora,
    faRProject,
    faRaspberryPi,
    faRavelry,
    faReact,
    faReacteurope,
    faReadme,
    faRebel,
    faRedRiver,
    faReddit,
    faRedditAlien,
    faRedditSquare,
    faRedhat,
    faRenren,
    faReplyd,
    faResearchgate,
    faResolving,
    faRev,
    faRocketchat,
    faRockrms,
    faRust,
    faSafari,
    faSalesforce,
    faSass,
    faSchlix,
    faScribd,
    faSearchengin,
    faSellcast,
    faSellsy,
    faServicestack,
    faShirtsinbulk,
    faShopify,
    faShopware,
    faSimplybuilt,
    faSistrix,
    faSith,
    faSketch,
    faSkyatlas,
    faSkype,
    faSlack,
    faSlackHash,
    faSlideshare,
    faSnapchat,
    faSnapchatGhost,
    faSnapchatSquare,
    faSoundcloud,
    faSourcetree,
    faSpeakap,
    faSpeakerDeck,
    faSpotify,
    faSquarespace,
    faStackExchange,
    faStackOverflow,
    faStackpath,
    faStaylinked,
    faSteam,
    faSteamSquare,
    faSteamSymbol,
    faStickerMule,
    faStrava,
    faStripe,
    faStripeS,
    faStudiovinari,
    faStumbleupon,
    faStumbleuponCircle,
    faSuperpowers,
    faSupple,
    faSuse,
    faSwift,
    faSymfony,
    faTeamspeak,
    faTelegram,
    faTelegramPlane,
    faTencentWeibo,
    faTheRedYeti,
    faThemeco,
    faThemeisle,
    faThinkPeaks,
    faTiktok,
    faTradeFederation,
    faTrello,
    faTripadvisor,
    faTumblr,
    faTumblrSquare,
    faTwitch,
    faTwitter,
    faTwitterSquare,
    faTypo3,
    faUber,
    faUbuntu,
    faUikit,
    faUmbraco,
    faUncharted,
    faUniregistry,
    faUnity,
    faUnsplash,
    faUntappd,
    faUps,
    faUsb,
    faUsps,
    faUssunnah,
    faVaadin,
    faViacoin,
    faViadeo,
    faViadeoSquare,
    faViber,
    faVimeo,
    faVimeoSquare,
    faVimeoV,
    faVine,
    faVk,
    faVnv,
    faVuejs,
    faWatchmanMonitoring,
    faWaze,
    faWeebly,
    faWeibo,
    faWeixin,
    faWhatsapp,
    faWhatsappSquare,
    faWhmcs,
    faWikipediaW,
    faWindows,
    faWix,
    faWizardsOfTheCoast,
    faWodu,
    faWolfPackBattalion,
    faWordpress,
    faWordpressSimple,
    faWpbeginner,
    faWpexplorer,
    faWpforms,
    faWpressr,
    faXbox,
    faXing,
    faXingSquare,
    faYCombinator,
    faYahoo,
    faYammer,
    faYandex,
    faYandexInternational,
    faYarn,
    faYelp,
    faYoast,
    faYoutube,
    faYoutubeSquare,
    faZhihu
} from "@fortawesome/free-brands-svg-icons";
import {
    faAd,
    faAddressBook,
    faAddressCard,
    faAdjust,
    faAirFreshener,
    faAlignCenter,
    faAlignJustify,
    faAlignLeft,
    faAlignRight,
    faAllergies,
    faAmbulance,
    faAmericanSignLanguageInterpreting,
    faAnchor,
    faAngleDoubleDown,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleDoubleUp,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faAngry,
    faAnkh,
    faAppleAlt,
    faArchive,
    faArchway,
    faArrowAltCircleDown,
    faArrowAltCircleLeft,
    faArrowAltCircleRight,
    faArrowAltCircleUp,
    faArrowCircleDown,
    faArrowCircleLeft,
    faArrowCircleRight,
    faArrowCircleUp,
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowsAlt,
    faArrowsAltH,
    faArrowsAltV,
    faAssistiveListeningSystems,
    faAsterisk,
    faAt,
    faAtlas,
    faAtom,
    faAudioDescription,
    faAward,
    faBaby,
    faBabyCarriage,
    faBackspace,
    faBackward,
    faBacon,
    faBacteria,
    faBacterium,
    faBahai,
    faBalanceScale,
    faBalanceScaleLeft,
    faBalanceScaleRight,
    faBan,
    faBandAid,
    faBarcode,
    faBars,
    faBaseballBall,
    faBasketballBall,
    faBath,
    faBatteryEmpty,
    faBatteryFull,
    faBatteryHalf,
    faBatteryQuarter,
    faBatteryThreeQuarters,
    faBed,
    faBeer,
    faBell,
    faBellSlash,
    faBezierCurve,
    faBible,
    faBicycle,
    faBiking,
    faBinoculars,
    faBiohazard,
    faBirthdayCake,
    faBlender,
    faBlenderPhone,
    faBlind,
    faBlog,
    faBold,
    faBolt,
    faBomb,
    faBone,
    faBong,
    faBook,
    faBookDead,
    faBookMedical,
    faBookOpen,
    faBookReader,
    faBookmark,
    faBorderAll,
    faBorderNone,
    faBorderStyle,
    faBowlingBall,
    faBox,
    faBoxOpen,
    faBoxTissue,
    faBoxes,
    faBraille,
    faBrain,
    faBreadSlice,
    faBriefcase,
    faBriefcaseMedical,
    faBroadcastTower,
    faBroom,
    faBrush,
    faBug,
    faBuilding,
    faBullhorn,
    faBullseye,
    faBurn,
    faBus,
    faBusAlt,
    faBusinessTime,
    faCalculator,
    faCalendar,
    faCalendarAlt,
    faCalendarCheck,
    faCalendarDay,
    faCalendarMinus,
    faCalendarPlus,
    faCalendarTimes,
    faCalendarWeek,
    faCamera,
    faCameraRetro,
    faCampground,
    faCandyCane,
    faCannabis,
    faCapsules,
    faCar,
    faCarAlt,
    faCarBattery,
    faCarCrash,
    faCarSide,
    faCaravan,
    faCaretDown,
    faCaretLeft,
    faCaretRight,
    faCaretSquareDown,
    faCaretSquareLeft,
    faCaretSquareRight,
    faCaretSquareUp,
    faCaretUp,
    faCarrot,
    faCartArrowDown,
    faCartPlus,
    faCashRegister,
    faCat,
    faCertificate,
    faChair,
    faChalkboard,
    faChalkboardTeacher,
    faChargingStation,
    faChartArea,
    faChartBar,
    faChartLine,
    faChartPie,
    faCheck,
    faCheckCircle,
    faCheckDouble,
    faCheckSquare,
    faCheese,
    faChess,
    faChessBishop,
    faChessBoard,
    faChessKing,
    faChessKnight,
    faChessPawn,
    faChessQueen,
    faChessRook,
    faChevronCircleDown,
    faChevronCircleLeft,
    faChevronCircleRight,
    faChevronCircleUp,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChild,
    faChurch,
    faCircle,
    faCircleNotch,
    faCity,
    faClinicMedical,
    faClipboard,
    faClipboardCheck,
    faClipboardList,
    faClock,
    faClone,
    faClosedCaptioning,
    faCloud,
    faCloudDownloadAlt,
    faCloudMeatball,
    faCloudMoon,
    faCloudMoonRain,
    faCloudRain,
    faCloudShowersHeavy,
    faCloudSun,
    faCloudSunRain,
    faCloudUploadAlt,
    faCocktail,
    faCode,
    faCodeBranch,
    faCoffee,
    faCog,
    faCogs,
    faCoins,
    faColumns,
    faComment,
    faCommentAlt,
    faCommentDollar,
    faCommentDots,
    faCommentMedical,
    faCommentSlash,
    faComments,
    faCommentsDollar,
    faCompactDisc,
    faCompass,
    faCompress,
    faCompressAlt,
    faCompressArrowsAlt,
    faConciergeBell,
    faCookie,
    faCookieBite,
    faCopy,
    faCopyright,
    faCouch,
    faCreditCard,
    faCrop,
    faCropAlt,
    faCross,
    faCrosshairs,
    faCrow,
    faCrown,
    faCrutch,
    faCube,
    faCubes,
    faCut,
    faDatabase,
    faDeaf,
    faDemocrat,
    faDesktop,
    faDharmachakra,
    faDiagnoses,
    faDice,
    faDiceD20,
    faDiceD6,
    faDiceFive,
    faDiceFour,
    faDiceOne,
    faDiceSix,
    faDiceThree,
    faDiceTwo,
    faDigitalTachograph,
    faDirections,
    faDisease,
    faDivide,
    faDizzy,
    faDna,
    faDog,
    faDollarSign,
    faDolly,
    faDollyFlatbed,
    faDonate,
    faDoorClosed,
    faDoorOpen,
    faDotCircle,
    faDove,
    faDownload,
    faDraftingCompass,
    faDragon,
    faDrawPolygon,
    faDrum,
    faDrumSteelpan,
    faDrumstickBite,
    faDumbbell,
    faDumpster,
    faDumpsterFire,
    faDungeon,
    faEdit,
    faEgg,
    faEject,
    faEllipsisH,
    faEllipsisV,
    faEnvelope,
    faEnvelopeOpen,
    faEnvelopeOpenText,
    faEnvelopeSquare,
    faEquals,
    faEraser,
    faEthernet,
    faEuroSign,
    faExchangeAlt,
    faExclamation,
    faExclamationCircle,
    faExclamationTriangle,
    faExpand,
    faExpandAlt,
    faExpandArrowsAlt,
    faExternalLinkAlt,
    faExternalLinkSquareAlt,
    faEye,
    faEyeDropper,
    faEyeSlash,
    faFan,
    faFastBackward,
    faFastForward,
    faFaucet,
    faFax,
    faFeather,
    faFeatherAlt,
    faFemale,
    faFighterJet,
    faFile,
    faFileAlt,
    faFileArchive,
    faFileAudio,
    faFileCode,
    faFileContract,
    faFileCsv,
    faFileDownload,
    faFileExcel,
    faFileExport,
    faFileImage,
    faFileImport,
    faFileInvoice,
    faFileInvoiceDollar,
    faFileMedical,
    faFileMedicalAlt,
    faFilePdf,
    faFilePowerpoint,
    faFilePrescription,
    faFileSignature,
    faFileUpload,
    faFileVideo,
    faFileWord,
    faFill,
    faFillDrip,
    faFilm,
    faFilter,
    faFingerprint,
    faFire,
    faFireAlt,
    faFireExtinguisher,
    faFirstAid,
    faFish,
    faFistRaised,
    faFlag,
    faFlagCheckered,
    faFlagUsa,
    faFlask,
    faFlushed,
    faFolder,
    faFolderMinus,
    faFolderOpen,
    faFolderPlus,
    faFont,
    faFootballBall,
    faForward,
    faFrog,
    faFrown,
    faFrownOpen,
    faFunnelDollar,
    faFutbol,
    faGamepad,
    faGasPump,
    faGavel,
    faGem,
    faGenderless,
    faGhost,
    faGift,
    faGifts,
    faGlassCheers,
    faGlassMartini,
    faGlassMartiniAlt,
    faGlassWhiskey,
    faGlasses,
    faGlobe,
    faGlobeAfrica,
    faGlobeAmericas,
    faGlobeAsia,
    faGlobeEurope,
    faGolfBall,
    faGopuram,
    faGraduationCap,
    faGreaterThan,
    faGreaterThanEqual,
    faGrimace,
    faGrin,
    faGrinAlt,
    faGrinBeam,
    faGrinBeamSweat,
    faGrinHearts,
    faGrinSquint,
    faGrinSquintTears,
    faGrinStars,
    faGrinTears,
    faGrinTongue,
    faGrinTongueSquint,
    faGrinTongueWink,
    faGrinWink,
    faGripHorizontal,
    faGripLines,
    faGripLinesVertical,
    faGripVertical,
    faGuitar,
    faHSquare,
    faHamburger,
    faHammer,
    faHamsa,
    faHandHolding,
    faHandHoldingHeart,
    faHandHoldingMedical,
    faHandHoldingUsd,
    faHandHoldingWater,
    faHandLizard,
    faHandMiddleFinger,
    faHandPaper,
    faHandPeace,
    faHandPointDown,
    faHandPointLeft,
    faHandPointRight,
    faHandPointUp,
    faHandPointer,
    faHandRock,
    faHandScissors,
    faHandSparkles,
    faHandSpock,
    faHands,
    faHandsHelping,
    faHandsWash,
    faHandshake,
    faHandshakeAltSlash,
    faHandshakeSlash,
    faHanukiah,
    faHardHat,
    faHashtag,
    faHatCowboy,
    faHatCowboySide,
    faHatWizard,
    faHdd,
    faHeadSideCough,
    faHeadSideCoughSlash,
    faHeadSideMask,
    faHeadSideVirus,
    faHeading,
    faHeadphones,
    faHeadphonesAlt,
    faHeadset,
    faHeart,
    faHeartBroken,
    faHeartbeat,
    faHelicopter,
    faHighlighter,
    faHiking,
    faHippo,
    faHistory,
    faHockeyPuck,
    faHollyBerry,
    faHome,
    faHorse,
    faHorseHead,
    faHospital,
    faHospitalAlt,
    faHospitalSymbol,
    faHospitalUser,
    faHotTub,
    faHotdog,
    faHotel,
    faHourglass,
    faHourglassEnd,
    faHourglassHalf,
    faHourglassStart,
    faHouseDamage,
    faHouseUser,
    faHryvnia,
    faICursor,
    faIceCream,
    faIcicles,
    faIcons,
    faIdBadge,
    faIdCard,
    faIdCardAlt,
    faIgloo,
    faImage,
    faImages,
    faInbox,
    faIndent,
    faIndustry,
    faInfinity,
    faInfo,
    faInfoCircle,
    faItalic,
    faJedi,
    faJoint,
    faJournalWhills,
    faKaaba,
    faKey,
    faKeyboard,
    faKhanda,
    faKiss,
    faKissBeam,
    faKissWinkHeart,
    faKiwiBird,
    faLandmark,
    faLanguage,
    faLaptop,
    faLaptopCode,
    faLaptopHouse,
    faLaptopMedical,
    faLaugh,
    faLaughBeam,
    faLaughSquint,
    faLaughWink,
    faLayerGroup,
    faLeaf,
    faLemon,
    faLessThan,
    faLessThanEqual,
    faLevelDownAlt,
    faLevelUpAlt,
    faLifeRing,
    faLightbulb,
    faLink,
    faLiraSign,
    faList,
    faListAlt,
    faListOl,
    faListUl,
    faLocationArrow,
    faLock,
    faLockOpen,
    faLongArrowAltDown,
    faLongArrowAltLeft,
    faLongArrowAltRight,
    faLongArrowAltUp,
    faLowVision,
    faLuggageCart,
    faLungs,
    faLungsVirus,
    faMagic,
    faMagnet,
    faMailBulk,
    faMale,
    faMap,
    faMapMarked,
    faMapMarkedAlt,
    faMapMarker,
    faMapMarkerAlt,
    faMapPin,
    faMapSigns,
    faMarker,
    faMars,
    faMarsDouble,
    faMarsStroke,
    faMarsStrokeH,
    faMarsStrokeV,
    faMask,
    faMedal,
    faMedkit,
    faMeh,
    faMehBlank,
    faMehRollingEyes,
    faMemory,
    faMenorah,
    faMercury,
    faMeteor,
    faMicrochip,
    faMicrophone,
    faMicrophoneAlt,
    faMicrophoneAltSlash,
    faMicrophoneSlash,
    faMicroscope,
    faMinus,
    faMinusCircle,
    faMinusSquare,
    faMitten,
    faMobile,
    faMobileAlt,
    faMoneyBill,
    faMoneyBillAlt,
    faMoneyBillWave,
    faMoneyBillWaveAlt,
    faMoneyCheck,
    faMoneyCheckAlt,
    faMonument,
    faMoon,
    faMortarPestle,
    faMosque,
    faMotorcycle,
    faMountain,
    faMouse,
    faMousePointer,
    faMugHot,
    faMusic,
    faNetworkWired,
    faNeuter,
    faNewspaper,
    faNotEqual,
    faNotesMedical,
    faObjectGroup,
    faObjectUngroup,
    faOilCan,
    faOm,
    faOtter,
    faOutdent,
    faPager,
    faPaintBrush,
    faPaintRoller,
    faPalette,
    faPallet,
    faPaperPlane,
    faPaperclip,
    faParachuteBox,
    faParagraph,
    faParking,
    faPassport,
    faPastafarianism,
    faPaste,
    faPause,
    faPauseCircle,
    faPaw,
    faPeace,
    faPen,
    faPenAlt,
    faPenFancy,
    faPenNib,
    faPenSquare,
    faPencilAlt,
    faPencilRuler,
    faPeopleArrows,
    faPeopleCarry,
    faPepperHot,
    faPercent,
    faPercentage,
    faPersonBooth,
    faPhone,
    faPhoneAlt,
    faPhoneSlash,
    faPhoneSquare,
    faPhoneSquareAlt,
    faPhoneVolume,
    faPhotoVideo,
    faPiggyBank,
    faPills,
    faPizzaSlice,
    faPlaceOfWorship,
    faPlane,
    faPlaneArrival,
    faPlaneDeparture,
    faPlaneSlash,
    faPlay,
    faPlayCircle,
    faPlug,
    faPlus,
    faPlusCircle,
    faPlusSquare,
    faPodcast,
    faPoll,
    faPollH,
    faPoo,
    faPooStorm,
    faPoop,
    faPortrait,
    faPoundSign,
    faPowerOff,
    faPray,
    faPrayingHands,
    faPrescription,
    faPrescriptionBottle,
    faPrescriptionBottleAlt,
    faPrint,
    faProcedures,
    faProjectDiagram,
    faPumpMedical,
    faPumpSoap,
    faPuzzlePiece,
    faQrcode,
    faQuestion,
    faQuestionCircle,
    faQuidditch,
    faQuoteLeft,
    faQuoteRight,
    faQuran,
    faRadiation,
    faRadiationAlt,
    faRainbow,
    faRandom,
    faReceipt,
    faRecordVinyl,
    faRecycle,
    faRedo,
    faRedoAlt,
    faRegistered,
    faRemoveFormat,
    faReply,
    faReplyAll,
    faRepublican,
    faRestroom,
    faRetweet,
    faRibbon,
    faRing,
    faRoad,
    faRobot,
    faRocket,
    faRoute,
    faRss,
    faRssSquare,
    faRubleSign,
    faRuler,
    faRulerCombined,
    faRulerHorizontal,
    faRulerVertical,
    faRunning,
    faRupeeSign,
    faSadCry,
    faSadTear,
    faSatellite,
    faSatelliteDish,
    faSave,
    faSchool,
    faScrewdriver,
    faScroll,
    faSdCard,
    faSearch,
    faSearchDollar,
    faSearchLocation,
    faSearchMinus,
    faSearchPlus,
    faSeedling,
    faServer,
    faShapes,
    faShare,
    faShareAlt,
    faShareAltSquare,
    faShareSquare,
    faShekelSign,
    faShieldAlt,
    faShieldVirus,
    faShip,
    faShippingFast,
    faShoePrints,
    faShoppingBag,
    faShoppingBasket,
    faShoppingCart,
    faShower,
    faShuttleVan,
    faSign,
    faSignInAlt,
    faSignLanguage,
    faSignOutAlt,
    faSignal,
    faSignature,
    faSimCard,
    faSink,
    faSitemap,
    faSkating,
    faSkiing,
    faSkiingNordic,
    faSkull,
    faSkullCrossbones,
    faSlash,
    faSleigh,
    faSlidersH,
    faSmile,
    faSmileBeam,
    faSmileWink,
    faSmog,
    faSmoking,
    faSmokingBan,
    faSms,
    faSnowboarding,
    faSnowflake,
    faSnowman,
    faSnowplow,
    faSoap,
    faSocks,
    faSolarPanel,
    faSort,
    faSortAlphaDown,
    faSortAlphaDownAlt,
    faSortAlphaUp,
    faSortAlphaUpAlt,
    faSortAmountDown,
    faSortAmountDownAlt,
    faSortAmountUp,
    faSortAmountUpAlt,
    faSortDown,
    faSortNumericDown,
    faSortNumericDownAlt,
    faSortNumericUp,
    faSortNumericUpAlt,
    faSortUp,
    faSpa,
    faSpaceShuttle,
    faSpellCheck,
    faSpider,
    faSpinner,
    faSplotch,
    faSprayCan,
    faSquare,
    faSquareFull,
    faSquareRootAlt,
    faStamp,
    faStar,
    faStarAndCrescent,
    faStarHalf,
    faStarHalfAlt,
    faStarOfDavid,
    faStarOfLife,
    faStepBackward,
    faStepForward,
    faStethoscope,
    faStickyNote,
    faStop,
    faStopCircle,
    faStopwatch,
    faStopwatch20,
    faStore,
    faStoreAlt,
    faStoreAltSlash,
    faStoreSlash,
    faStream,
    faStreetView,
    faStrikethrough,
    faStroopwafel,
    faSubscript,
    faSubway,
    faSuitcase,
    faSuitcaseRolling,
    faSun,
    faSuperscript,
    faSurprise,
    faSwatchbook,
    faSwimmer,
    faSwimmingPool,
    faSynagogue,
    faSync,
    faSyncAlt,
    faSyringe,
    faTable,
    faTableTennis,
    faTablet,
    faTabletAlt,
    faTablets,
    faTachometerAlt,
    faTag,
    faTags,
    faTape,
    faTasks,
    faTaxi,
    faTeeth,
    faTeethOpen,
    faTemperatureHigh,
    faTemperatureLow,
    faTenge,
    faTerminal,
    faTextHeight,
    faTextWidth,
    faTh,
    faThLarge,
    faThList,
    faTheaterMasks,
    faThermometer,
    faThermometerEmpty,
    faThermometerFull,
    faThermometerHalf,
    faThermometerQuarter,
    faThermometerThreeQuarters,
    faThumbsDown,
    faThumbsUp,
    faThumbtack,
    faTicketAlt,
    faTimes,
    faTimesCircle,
    faTint,
    faTintSlash,
    faTired,
    faToggleOff,
    faToggleOn,
    faToilet,
    faToiletPaper,
    faToiletPaperSlash,
    faToolbox,
    faTools,
    faTooth,
    faTorah,
    faToriiGate,
    faTractor,
    faTrademark,
    faTrafficLight,
    faTrailer,
    faTrain,
    faTram,
    faTransgender,
    faTransgenderAlt,
    faTrash,
    faTrashAlt,
    faTrashRestore,
    faTrashRestoreAlt,
    faTree,
    faTrophy,
    faTruck,
    faTruckLoading,
    faTruckMonster,
    faTruckMoving,
    faTruckPickup,
    faTshirt,
    faTty,
    faTv,
    faUmbrella,
    faUmbrellaBeach,
    faUnderline,
    faUndo,
    faUndoAlt,
    faUniversalAccess,
    faUniversity,
    faUnlink,
    faUnlock,
    faUnlockAlt,
    faUpload,
    faUser,
    faUserAlt,
    faUserAltSlash,
    faUserAstronaut,
    faUserCheck,
    faUserCircle,
    faUserClock,
    faUserCog,
    faUserEdit,
    faUserFriends,
    faUserGraduate,
    faUserInjured,
    faUserLock,
    faUserMd,
    faUserMinus,
    faUserNinja,
    faUserNurse,
    faUserPlus,
    faUserSecret,
    faUserShield,
    faUserSlash,
    faUserTag,
    faUserTie,
    faUserTimes,
    faUsers,
    faUsersCog,
    faUsersSlash,
    faUtensilSpoon,
    faUtensils,
    faVectorSquare,
    faVenus,
    faVenusDouble,
    faVenusMars,
    faVest,
    faVestPatches,
    faVial,
    faVials,
    faVideo,
    faVideoSlash,
    faVihara,
    faVirus,
    faVirusSlash,
    faViruses,
    faVoicemail,
    faVolleyballBall,
    faVolumeDown,
    faVolumeMute,
    faVolumeOff,
    faVolumeUp,
    faVoteYea,
    faVrCardboard,
    faWalking,
    faWallet,
    faWarehouse,
    faWater,
    faWaveSquare,
    faWeight,
    faWeightHanging,
    faWheelchair,
    faWifi,
    faWind,
    faWindowClose,
    faWindowMaximize,
    faWindowMinimize,
    faWindowRestore,
    faWineBottle,
    faWineGlass,
    faWineGlassAlt,
    faWonSign,
    faWrench,
    faXRay,
    faYenSign,
    faYinYang
} from "@fortawesome/free-solid-svg-icons";

export const FontAwesome = {
    faAd: faAd,
    faAddressBook: faAddressBook,
    faAddressCard: faAddressCard,
    faAdjust: faAdjust,
    faAirFreshener: faAirFreshener,
    faAlignCenter: faAlignCenter,
    faAlignJustify: faAlignJustify,
    faAlignLeft: faAlignLeft,
    faAlignRight: faAlignRight,
    faAllergies: faAllergies,
    faAmbulance: faAmbulance,
    faAmericanSignLanguageInterpreting: faAmericanSignLanguageInterpreting,
    faAnchor: faAnchor,
    faAngleDoubleDown: faAngleDoubleDown,
    faAngleDoubleLeft: faAngleDoubleLeft,
    faAngleDoubleRight: faAngleDoubleRight,
    faAngleDoubleUp: faAngleDoubleUp,
    faAngleDown: faAngleDown,
    faAngleLeft: faAngleLeft,
    faAngleRight: faAngleRight,
    faAngleUp: faAngleUp,
    faAngry: faAngry,
    faAnkh: faAnkh,
    faAppleAlt: faAppleAlt,
    faArchive: faArchive,
    faArchway: faArchway,
    faArrowAltCircleDown: faArrowAltCircleDown,
    faArrowAltCircleLeft: faArrowAltCircleLeft,
    faArrowAltCircleRight: faArrowAltCircleRight,
    faArrowAltCircleUp: faArrowAltCircleUp,
    faArrowCircleDown: faArrowCircleDown,
    faArrowCircleLeft: faArrowCircleLeft,
    faArrowCircleRight: faArrowCircleRight,
    faArrowCircleUp: faArrowCircleUp,
    faArrowDown: faArrowDown,
    faArrowLeft: faArrowLeft,
    faArrowRight: faArrowRight,
    faArrowUp: faArrowUp,
    faArrowsAlt: faArrowsAlt,
    faArrowsAltH: faArrowsAltH,
    faArrowsAltV: faArrowsAltV,
    faAssistiveListeningSystems: faAssistiveListeningSystems,
    faAsterisk: faAsterisk,
    faAt: faAt,
    faAtlas: faAtlas,
    faAtom: faAtom,
    faAudioDescription: faAudioDescription,
    faAward: faAward,
    faBaby: faBaby,
    faBabyCarriage: faBabyCarriage,
    faBackspace: faBackspace,
    faBackward: faBackward,
    faBacon: faBacon,
    faBacteria: faBacteria,
    faBacterium: faBacterium,
    faBahai: faBahai,
    faBalanceScale: faBalanceScale,
    faBalanceScaleLeft: faBalanceScaleLeft,
    faBalanceScaleRight: faBalanceScaleRight,
    faBan: faBan,
    faBandAid: faBandAid,
    faBarcode: faBarcode,
    faBars: faBars,
    faBaseballBall: faBaseballBall,
    faBasketballBall: faBasketballBall,
    faBath: faBath,
    faBatteryEmpty: faBatteryEmpty,
    faBatteryFull: faBatteryFull,
    faBatteryHalf: faBatteryHalf,
    faBatteryQuarter: faBatteryQuarter,
    faBatteryThreeQuarters: faBatteryThreeQuarters,
    faBed: faBed,
    faBeer: faBeer,
    faBell: faBell,
    faBellSlash: faBellSlash,
    faBezierCurve: faBezierCurve,
    faBible: faBible,
    faBicycle: faBicycle,
    faBiking: faBiking,
    faBinoculars: faBinoculars,
    faBiohazard: faBiohazard,
    faBirthdayCake: faBirthdayCake,
    faBlender: faBlender,
    faBlenderPhone: faBlenderPhone,
    faBlind: faBlind,
    faBlog: faBlog,
    faBold: faBold,
    faBolt: faBolt,
    faBomb: faBomb,
    faBone: faBone,
    faBong: faBong,
    faBook: faBook,
    faBookDead: faBookDead,
    faBookMedical: faBookMedical,
    faBookOpen: faBookOpen,
    faBookReader: faBookReader,
    faBookmark: faBookmark,
    faBorderAll: faBorderAll,
    faBorderNone: faBorderNone,
    faBorderStyle: faBorderStyle,
    faBowlingBall: faBowlingBall,
    faBox: faBox,
    faBoxOpen: faBoxOpen,
    faBoxTissue: faBoxTissue,
    faBoxes: faBoxes,
    faBraille: faBraille,
    faBrain: faBrain,
    faBreadSlice: faBreadSlice,
    faBriefcase: faBriefcase,
    faBriefcaseMedical: faBriefcaseMedical,
    faBroadcastTower: faBroadcastTower,
    faBroom: faBroom,
    faBrush: faBrush,
    faBug: faBug,
    faBuilding: faBuilding,
    faBullhorn: faBullhorn,
    faBullseye: faBullseye,
    faBurn: faBurn,
    faBus: faBus,
    faBusAlt: faBusAlt,
    faBusinessTime: faBusinessTime,
    faCalculator: faCalculator,
    faCalendar: faCalendar,
    faCalendarAlt: faCalendarAlt,
    faCalendarCheck: faCalendarCheck,
    faCalendarDay: faCalendarDay,
    faCalendarMinus: faCalendarMinus,
    faCalendarPlus: faCalendarPlus,
    faCalendarTimes: faCalendarTimes,
    faCalendarWeek: faCalendarWeek,
    faCamera: faCamera,
    faCameraRetro: faCameraRetro,
    faCampground: faCampground,
    faCandyCane: faCandyCane,
    faCannabis: faCannabis,
    faCapsules: faCapsules,
    faCar: faCar,
    faCarAlt: faCarAlt,
    faCarBattery: faCarBattery,
    faCarCrash: faCarCrash,
    faCarSide: faCarSide,
    faCaravan: faCaravan,
    faCaretDown: faCaretDown,
    faCaretLeft: faCaretLeft,
    faCaretRight: faCaretRight,
    faCaretSquareDown: faCaretSquareDown,
    faCaretSquareLeft: faCaretSquareLeft,
    faCaretSquareRight: faCaretSquareRight,
    faCaretSquareUp: faCaretSquareUp,
    faCaretUp: faCaretUp,
    faCarrot: faCarrot,
    faCartArrowDown: faCartArrowDown,
    faCartPlus: faCartPlus,
    faCashRegister: faCashRegister,
    faCat: faCat,
    faCertificate: faCertificate,
    faChair: faChair,
    faChalkboard: faChalkboard,
    faChalkboardTeacher: faChalkboardTeacher,
    faChargingStation: faChargingStation,
    faChartArea: faChartArea,
    faChartBar: faChartBar,
    faChartLine: faChartLine,
    faChartPie: faChartPie,
    faCheck: faCheck,
    faCheckCircle: faCheckCircle,
    faCheckDouble: faCheckDouble,
    faCheckSquare: faCheckSquare,
    faCheese: faCheese,
    faChess: faChess,
    faChessBishop: faChessBishop,
    faChessBoard: faChessBoard,
    faChessKing: faChessKing,
    faChessKnight: faChessKnight,
    faChessPawn: faChessPawn,
    faChessQueen: faChessQueen,
    faChessRook: faChessRook,
    faChevronCircleDown: faChevronCircleDown,
    faChevronCircleLeft: faChevronCircleLeft,
    faChevronCircleRight: faChevronCircleRight,
    faChevronCircleUp: faChevronCircleUp,
    faChevronDown: faChevronDown,
    faChevronLeft: faChevronLeft,
    faChevronRight: faChevronRight,
    faChevronUp: faChevronUp,
    faChild: faChild,
    faChurch: faChurch,
    faCircle: faCircle,
    faCircleNotch: faCircleNotch,
    faCity: faCity,
    faClinicMedical: faClinicMedical,
    faClipboard: faClipboard,
    faClipboardCheck: faClipboardCheck,
    faClipboardList: faClipboardList,
    faClock: faClock,
    faClone: faClone,
    faClosedCaptioning: faClosedCaptioning,
    faCloud: faCloud,
    faCloudDownloadAlt: faCloudDownloadAlt,
    faCloudMeatball: faCloudMeatball,
    faCloudMoon: faCloudMoon,
    faCloudMoonRain: faCloudMoonRain,
    faCloudRain: faCloudRain,
    faCloudShowersHeavy: faCloudShowersHeavy,
    faCloudSun: faCloudSun,
    faCloudSunRain: faCloudSunRain,
    faCloudUploadAlt: faCloudUploadAlt,
    faCocktail: faCocktail,
    faCode: faCode,
    faCodeBranch: faCodeBranch,
    faCoffee: faCoffee,
    faCog: faCog,
    faCogs: faCogs,
    faCoins: faCoins,
    faColumns: faColumns,
    faComment: faComment,
    faCommentAlt: faCommentAlt,
    faCommentDollar: faCommentDollar,
    faCommentDots: faCommentDots,
    faCommentMedical: faCommentMedical,
    faCommentSlash: faCommentSlash,
    faComments: faComments,
    faCommentsDollar: faCommentsDollar,
    faCompactDisc: faCompactDisc,
    faCompass: faCompass,
    faCompress: faCompress,
    faCompressAlt: faCompressAlt,
    faCompressArrowsAlt: faCompressArrowsAlt,
    faConciergeBell: faConciergeBell,
    faCookie: faCookie,
    faCookieBite: faCookieBite,
    faCopy: faCopy,
    faCopyright: faCopyright,
    faCouch: faCouch,
    faCreditCard: faCreditCard,
    faCrop: faCrop,
    faCropAlt: faCropAlt,
    faCross: faCross,
    faCrosshairs: faCrosshairs,
    faCrow: faCrow,
    faCrown: faCrown,
    faCrutch: faCrutch,
    faCube: faCube,
    faCubes: faCubes,
    faCut: faCut,
    faDatabase: faDatabase,
    faDeaf: faDeaf,
    faDemocrat: faDemocrat,
    faDesktop: faDesktop,
    faDharmachakra: faDharmachakra,
    faDiagnoses: faDiagnoses,
    faDice: faDice,
    faDiceD20: faDiceD20,
    faDiceD6: faDiceD6,
    faDiceFive: faDiceFive,
    faDiceFour: faDiceFour,
    faDiceOne: faDiceOne,
    faDiceSix: faDiceSix,
    faDiceThree: faDiceThree,
    faDiceTwo: faDiceTwo,
    faDigitalTachograph: faDigitalTachograph,
    faDirections: faDirections,
    faDisease: faDisease,
    faDivide: faDivide,
    faDizzy: faDizzy,
    faDna: faDna,
    faDog: faDog,
    faDollarSign: faDollarSign,
    faDolly: faDolly,
    faDollyFlatbed: faDollyFlatbed,
    faDonate: faDonate,
    faDoorClosed: faDoorClosed,
    faDoorOpen: faDoorOpen,
    faDotCircle: faDotCircle,
    faDove: faDove,
    faDownload: faDownload,
    faDraftingCompass: faDraftingCompass,
    faDragon: faDragon,
    faDrawPolygon: faDrawPolygon,
    faDrum: faDrum,
    faDrumSteelpan: faDrumSteelpan,
    faDrumstickBite: faDrumstickBite,
    faDumbbell: faDumbbell,
    faDumpster: faDumpster,
    faDumpsterFire: faDumpsterFire,
    faDungeon: faDungeon,
    faEdit: faEdit,
    faEgg: faEgg,
    faEject: faEject,
    faEllipsisH: faEllipsisH,
    faEllipsisV: faEllipsisV,
    faEnvelope: faEnvelope,
    faEnvelopeOpen: faEnvelopeOpen,
    faEnvelopeOpenText: faEnvelopeOpenText,
    faEnvelopeSquare: faEnvelopeSquare,
    faEquals: faEquals,
    faEraser: faEraser,
    faEthernet: faEthernet,
    faEuroSign: faEuroSign,
    faExchangeAlt: faExchangeAlt,
    faExclamation: faExclamation,
    faExclamationCircle: faExclamationCircle,
    faExclamationTriangle: faExclamationTriangle,
    faExpand: faExpand,
    faExpandAlt: faExpandAlt,
    faExpandArrowsAlt: faExpandArrowsAlt,
    faExternalLinkAlt: faExternalLinkAlt,
    faExternalLinkSquareAlt: faExternalLinkSquareAlt,
    faEye: faEye,
    faEyeDropper: faEyeDropper,
    faEyeSlash: faEyeSlash,
    faFan: faFan,
    faFastBackward: faFastBackward,
    faFastForward: faFastForward,
    faFaucet: faFaucet,
    faFax: faFax,
    faFeather: faFeather,
    faFeatherAlt: faFeatherAlt,
    faFemale: faFemale,
    faFighterJet: faFighterJet,
    faFile: faFile,
    faFileAlt: faFileAlt,
    faFileArchive: faFileArchive,
    faFileAudio: faFileAudio,
    faFileCode: faFileCode,
    faFileContract: faFileContract,
    faFileCsv: faFileCsv,
    faFileDownload: faFileDownload,
    faFileExcel: faFileExcel,
    faFileExport: faFileExport,
    faFileImage: faFileImage,
    faFileImport: faFileImport,
    faFileInvoice: faFileInvoice,
    faFileInvoiceDollar: faFileInvoiceDollar,
    faFileMedical: faFileMedical,
    faFileMedicalAlt: faFileMedicalAlt,
    faFilePdf: faFilePdf,
    faFilePowerpoint: faFilePowerpoint,
    faFilePrescription: faFilePrescription,
    faFileSignature: faFileSignature,
    faFileUpload: faFileUpload,
    faFileVideo: faFileVideo,
    faFileWord: faFileWord,
    faFill: faFill,
    faFillDrip: faFillDrip,
    faFilm: faFilm,
    faFilter: faFilter,
    faFingerprint: faFingerprint,
    faFire: faFire,
    faFireAlt: faFireAlt,
    faFireExtinguisher: faFireExtinguisher,
    faFirstAid: faFirstAid,
    faFish: faFish,
    faFistRaised: faFistRaised,
    faFlag: faFlag,
    faFlagCheckered: faFlagCheckered,
    faFlagUsa: faFlagUsa,
    faFlask: faFlask,
    faFlushed: faFlushed,
    faFolder: faFolder,
    faFolderMinus: faFolderMinus,
    faFolderOpen: faFolderOpen,
    faFolderPlus: faFolderPlus,
    faFont: faFont,
    faFootballBall: faFootballBall,
    faForward: faForward,
    faFrog: faFrog,
    faFrown: faFrown,
    faFrownOpen: faFrownOpen,
    faFunnelDollar: faFunnelDollar,
    faFutbol: faFutbol,
    faGamepad: faGamepad,
    faGasPump: faGasPump,
    faGavel: faGavel,
    faGem: faGem,
    faGenderless: faGenderless,
    faGhost: faGhost,
    faGift: faGift,
    faGifts: faGifts,
    faGlassCheers: faGlassCheers,
    faGlassMartini: faGlassMartini,
    faGlassMartiniAlt: faGlassMartiniAlt,
    faGlassWhiskey: faGlassWhiskey,
    faGlasses: faGlasses,
    faGlobe: faGlobe,
    faGlobeAfrica: faGlobeAfrica,
    faGlobeAmericas: faGlobeAmericas,
    faGlobeAsia: faGlobeAsia,
    faGlobeEurope: faGlobeEurope,
    faGolfBall: faGolfBall,
    faGopuram: faGopuram,
    faGraduationCap: faGraduationCap,
    faGreaterThan: faGreaterThan,
    faGreaterThanEqual: faGreaterThanEqual,
    faGrimace: faGrimace,
    faGrin: faGrin,
    faGrinAlt: faGrinAlt,
    faGrinBeam: faGrinBeam,
    faGrinBeamSweat: faGrinBeamSweat,
    faGrinHearts: faGrinHearts,
    faGrinSquint: faGrinSquint,
    faGrinSquintTears: faGrinSquintTears,
    faGrinStars: faGrinStars,
    faGrinTears: faGrinTears,
    faGrinTongue: faGrinTongue,
    faGrinTongueSquint: faGrinTongueSquint,
    faGrinTongueWink: faGrinTongueWink,
    faGrinWink: faGrinWink,
    faGripHorizontal: faGripHorizontal,
    faGripLines: faGripLines,
    faGripLinesVertical: faGripLinesVertical,
    faGripVertical: faGripVertical,
    faGuitar: faGuitar,
    faHSquare: faHSquare,
    faHamburger: faHamburger,
    faHammer: faHammer,
    faHamsa: faHamsa,
    faHandHolding: faHandHolding,
    faHandHoldingHeart: faHandHoldingHeart,
    faHandHoldingMedical: faHandHoldingMedical,
    faHandHoldingUsd: faHandHoldingUsd,
    faHandHoldingWater: faHandHoldingWater,
    faHandLizard: faHandLizard,
    faHandMiddleFinger: faHandMiddleFinger,
    faHandPaper: faHandPaper,
    faHandPeace: faHandPeace,
    faHandPointDown: faHandPointDown,
    faHandPointLeft: faHandPointLeft,
    faHandPointRight: faHandPointRight,
    faHandPointUp: faHandPointUp,
    faHandPointer: faHandPointer,
    faHandRock: faHandRock,
    faHandScissors: faHandScissors,
    faHandSparkles: faHandSparkles,
    faHandSpock: faHandSpock,
    faHands: faHands,
    faHandsHelping: faHandsHelping,
    faHandsWash: faHandsWash,
    faHandshake: faHandshake,
    faHandshakeAltSlash: faHandshakeAltSlash,
    faHandshakeSlash: faHandshakeSlash,
    faHanukiah: faHanukiah,
    faHardHat: faHardHat,
    faHashtag: faHashtag,
    faHatCowboy: faHatCowboy,
    faHatCowboySide: faHatCowboySide,
    faHatWizard: faHatWizard,
    faHdd: faHdd,
    faHeadSideCough: faHeadSideCough,
    faHeadSideCoughSlash: faHeadSideCoughSlash,
    faHeadSideMask: faHeadSideMask,
    faHeadSideVirus: faHeadSideVirus,
    faHeading: faHeading,
    faHeadphones: faHeadphones,
    faHeadphonesAlt: faHeadphonesAlt,
    faHeadset: faHeadset,
    faHeart: faHeart,
    faHeartBroken: faHeartBroken,
    faHeartbeat: faHeartbeat,
    faHelicopter: faHelicopter,
    faHighlighter: faHighlighter,
    faHiking: faHiking,
    faHippo: faHippo,
    faHistory: faHistory,
    faHockeyPuck: faHockeyPuck,
    faHollyBerry: faHollyBerry,
    faHome: faHome,
    faHorse: faHorse,
    faHorseHead: faHorseHead,
    faHospital: faHospital,
    faHospitalAlt: faHospitalAlt,
    faHospitalSymbol: faHospitalSymbol,
    faHospitalUser: faHospitalUser,
    faHotTub: faHotTub,
    faHotdog: faHotdog,
    faHotel: faHotel,
    faHourglass: faHourglass,
    faHourglassEnd: faHourglassEnd,
    faHourglassHalf: faHourglassHalf,
    faHourglassStart: faHourglassStart,
    faHouseDamage: faHouseDamage,
    faHouseUser: faHouseUser,
    faHryvnia: faHryvnia,
    faICursor: faICursor,
    faIceCream: faIceCream,
    faIcicles: faIcicles,
    faIcons: faIcons,
    faIdBadge: faIdBadge,
    faIdCard: faIdCard,
    faIdCardAlt: faIdCardAlt,
    faIgloo: faIgloo,
    faImage: faImage,
    faImages: faImages,
    faInbox: faInbox,
    faIndent: faIndent,
    faIndustry: faIndustry,
    faInfinity: faInfinity,
    faInfo: faInfo,
    faInfoCircle: faInfoCircle,
    faItalic: faItalic,
    faJedi: faJedi,
    faJoint: faJoint,
    faJournalWhills: faJournalWhills,
    faKaaba: faKaaba,
    faKey: faKey,
    faKeyboard: faKeyboard,
    faKhanda: faKhanda,
    faKiss: faKiss,
    faKissBeam: faKissBeam,
    faKissWinkHeart: faKissWinkHeart,
    faKiwiBird: faKiwiBird,
    faLandmark: faLandmark,
    faLanguage: faLanguage,
    faLaptop: faLaptop,
    faLaptopCode: faLaptopCode,
    faLaptopHouse: faLaptopHouse,
    faLaptopMedical: faLaptopMedical,
    faLaugh: faLaugh,
    faLaughBeam: faLaughBeam,
    faLaughSquint: faLaughSquint,
    faLaughWink: faLaughWink,
    faLayerGroup: faLayerGroup,
    faLeaf: faLeaf,
    faLemon: faLemon,
    faLessThan: faLessThan,
    faLessThanEqual: faLessThanEqual,
    faLevelDownAlt: faLevelDownAlt,
    faLevelUpAlt: faLevelUpAlt,
    faLifeRing: faLifeRing,
    faLightbulb: faLightbulb,
    faLink: faLink,
    faLiraSign: faLiraSign,
    faList: faList,
    faListAlt: faListAlt,
    faListOl: faListOl,
    faListUl: faListUl,
    faLocationArrow: faLocationArrow,
    faLock: faLock,
    faLockOpen: faLockOpen,
    faLongArrowAltDown: faLongArrowAltDown,
    faLongArrowAltLeft: faLongArrowAltLeft,
    faLongArrowAltRight: faLongArrowAltRight,
    faLongArrowAltUp: faLongArrowAltUp,
    faLowVision: faLowVision,
    faLuggageCart: faLuggageCart,
    faLungs: faLungs,
    faLungsVirus: faLungsVirus,
    faMagic: faMagic,
    faMagnet: faMagnet,
    faMailBulk: faMailBulk,
    faMale: faMale,
    faMap: faMap,
    faMapMarked: faMapMarked,
    faMapMarkedAlt: faMapMarkedAlt,
    faMapMarker: faMapMarker,
    faMapMarkerAlt: faMapMarkerAlt,
    faMapPin: faMapPin,
    faMapSigns: faMapSigns,
    faMarker: faMarker,
    faMars: faMars,
    faMarsDouble: faMarsDouble,
    faMarsStroke: faMarsStroke,
    faMarsStrokeH: faMarsStrokeH,
    faMarsStrokeV: faMarsStrokeV,
    faMask: faMask,
    faMedal: faMedal,
    faMedkit: faMedkit,
    faMeh: faMeh,
    faMehBlank: faMehBlank,
    faMehRollingEyes: faMehRollingEyes,
    faMemory: faMemory,
    faMenorah: faMenorah,
    faMercury: faMercury,
    faMeteor: faMeteor,
    faMicrochip: faMicrochip,
    faMicrophone: faMicrophone,
    faMicrophoneAlt: faMicrophoneAlt,
    faMicrophoneAltSlash: faMicrophoneAltSlash,
    faMicrophoneSlash: faMicrophoneSlash,
    faMicroscope: faMicroscope,
    faMinus: faMinus,
    faMinusCircle: faMinusCircle,
    faMinusSquare: faMinusSquare,
    faMitten: faMitten,
    faMobile: faMobile,
    faMobileAlt: faMobileAlt,
    faMoneyBill: faMoneyBill,
    faMoneyBillAlt: faMoneyBillAlt,
    faMoneyBillWave: faMoneyBillWave,
    faMoneyBillWaveAlt: faMoneyBillWaveAlt,
    faMoneyCheck: faMoneyCheck,
    faMoneyCheckAlt: faMoneyCheckAlt,
    faMonument: faMonument,
    faMoon: faMoon,
    faMortarPestle: faMortarPestle,
    faMosque: faMosque,
    faMotorcycle: faMotorcycle,
    faMountain: faMountain,
    faMouse: faMouse,
    faMousePointer: faMousePointer,
    faMugHot: faMugHot,
    faMusic: faMusic,
    faNetworkWired: faNetworkWired,
    faNeuter: faNeuter,
    faNewspaper: faNewspaper,
    faNotEqual: faNotEqual,
    faNotesMedical: faNotesMedical,
    faObjectGroup: faObjectGroup,
    faObjectUngroup: faObjectUngroup,
    faOilCan: faOilCan,
    faOm: faOm,
    faOtter: faOtter,
    faOutdent: faOutdent,
    faPager: faPager,
    faPaintBrush: faPaintBrush,
    faPaintRoller: faPaintRoller,
    faPalette: faPalette,
    faPallet: faPallet,
    faPaperPlane: faPaperPlane,
    faPaperclip: faPaperclip,
    faParachuteBox: faParachuteBox,
    faParagraph: faParagraph,
    faParking: faParking,
    faPassport: faPassport,
    faPastafarianism: faPastafarianism,
    faPaste: faPaste,
    faPause: faPause,
    faPauseCircle: faPauseCircle,
    faPaw: faPaw,
    faPeace: faPeace,
    faPen: faPen,
    faPenAlt: faPenAlt,
    faPenFancy: faPenFancy,
    faPenNib: faPenNib,
    faPenSquare: faPenSquare,
    faPencilAlt: faPencilAlt,
    faPencilRuler: faPencilRuler,
    faPeopleArrows: faPeopleArrows,
    faPeopleCarry: faPeopleCarry,
    faPepperHot: faPepperHot,
    faPercent: faPercent,
    faPercentage: faPercentage,
    faPersonBooth: faPersonBooth,
    faPhone: faPhone,
    faPhoneAlt: faPhoneAlt,
    faPhoneSlash: faPhoneSlash,
    faPhoneSquare: faPhoneSquare,
    faPhoneSquareAlt: faPhoneSquareAlt,
    faPhoneVolume: faPhoneVolume,
    faPhotoVideo: faPhotoVideo,
    faPiggyBank: faPiggyBank,
    faPills: faPills,
    faPizzaSlice: faPizzaSlice,
    faPlaceOfWorship: faPlaceOfWorship,
    faPlane: faPlane,
    faPlaneArrival: faPlaneArrival,
    faPlaneDeparture: faPlaneDeparture,
    faPlaneSlash: faPlaneSlash,
    faPlay: faPlay,
    faPlayCircle: faPlayCircle,
    faPlug: faPlug,
    faPlus: faPlus,
    faPlusCircle: faPlusCircle,
    faPlusSquare: faPlusSquare,
    faPodcast: faPodcast,
    faPoll: faPoll,
    faPollH: faPollH,
    faPoo: faPoo,
    faPooStorm: faPooStorm,
    faPoop: faPoop,
    faPortrait: faPortrait,
    faPoundSign: faPoundSign,
    faPowerOff: faPowerOff,
    faPray: faPray,
    faPrayingHands: faPrayingHands,
    faPrescription: faPrescription,
    faPrescriptionBottle: faPrescriptionBottle,
    faPrescriptionBottleAlt: faPrescriptionBottleAlt,
    faPrint: faPrint,
    faProcedures: faProcedures,
    faProjectDiagram: faProjectDiagram,
    faPumpMedical: faPumpMedical,
    faPumpSoap: faPumpSoap,
    faPuzzlePiece: faPuzzlePiece,
    faQrcode: faQrcode,
    faQuestion: faQuestion,
    faQuestionCircle: faQuestionCircle,
    faQuidditch: faQuidditch,
    faQuoteLeft: faQuoteLeft,
    faQuoteRight: faQuoteRight,
    faQuran: faQuran,
    faRadiation: faRadiation,
    faRadiationAlt: faRadiationAlt,
    faRainbow: faRainbow,
    faRandom: faRandom,
    faReceipt: faReceipt,
    faRecordVinyl: faRecordVinyl,
    faRecycle: faRecycle,
    faRedo: faRedo,
    faRedoAlt: faRedoAlt,
    faRegistered: faRegistered,
    faRemoveFormat: faRemoveFormat,
    faReply: faReply,
    faReplyAll: faReplyAll,
    faRepublican: faRepublican,
    faRestroom: faRestroom,
    faRetweet: faRetweet,
    faRibbon: faRibbon,
    faRing: faRing,
    faRoad: faRoad,
    faRobot: faRobot,
    faRocket: faRocket,
    faRoute: faRoute,
    faRss: faRss,
    faRssSquare: faRssSquare,
    faRubleSign: faRubleSign,
    faRuler: faRuler,
    faRulerCombined: faRulerCombined,
    faRulerHorizontal: faRulerHorizontal,
    faRulerVertical: faRulerVertical,
    faRunning: faRunning,
    faRupeeSign: faRupeeSign,
    faSadCry: faSadCry,
    faSadTear: faSadTear,
    faSatellite: faSatellite,
    faSatelliteDish: faSatelliteDish,
    faSave: faSave,
    faSchool: faSchool,
    faScrewdriver: faScrewdriver,
    faScroll: faScroll,
    faSdCard: faSdCard,
    faSearch: faSearch,
    faSearchDollar: faSearchDollar,
    faSearchLocation: faSearchLocation,
    faSearchMinus: faSearchMinus,
    faSearchPlus: faSearchPlus,
    faSeedling: faSeedling,
    faServer: faServer,
    faShapes: faShapes,
    faShare: faShare,
    faShareAlt: faShareAlt,
    faShareAltSquare: faShareAltSquare,
    faShareSquare: faShareSquare,
    faShekelSign: faShekelSign,
    faShieldAlt: faShieldAlt,
    faShieldVirus: faShieldVirus,
    faShip: faShip,
    faShippingFast: faShippingFast,
    faShoePrints: faShoePrints,
    faShoppingBag: faShoppingBag,
    faShoppingBasket: faShoppingBasket,
    faShoppingCart: faShoppingCart,
    faShower: faShower,
    faShuttleVan: faShuttleVan,
    faSign: faSign,
    faSignInAlt: faSignInAlt,
    faSignLanguage: faSignLanguage,
    faSignOutAlt: faSignOutAlt,
    faSignal: faSignal,
    faSignature: faSignature,
    faSimCard: faSimCard,
    faSink: faSink,
    faSitemap: faSitemap,
    faSkating: faSkating,
    faSkiing: faSkiing,
    faSkiingNordic: faSkiingNordic,
    faSkull: faSkull,
    faSkullCrossbones: faSkullCrossbones,
    faSlash: faSlash,
    faSleigh: faSleigh,
    faSlidersH: faSlidersH,
    faSmile: faSmile,
    faSmileBeam: faSmileBeam,
    faSmileWink: faSmileWink,
    faSmog: faSmog,
    faSmoking: faSmoking,
    faSmokingBan: faSmokingBan,
    faSms: faSms,
    faSnowboarding: faSnowboarding,
    faSnowflake: faSnowflake,
    faSnowman: faSnowman,
    faSnowplow: faSnowplow,
    faSoap: faSoap,
    faSocks: faSocks,
    faSolarPanel: faSolarPanel,
    faSort: faSort,
    faSortAlphaDown: faSortAlphaDown,
    faSortAlphaDownAlt: faSortAlphaDownAlt,
    faSortAlphaUp: faSortAlphaUp,
    faSortAlphaUpAlt: faSortAlphaUpAlt,
    faSortAmountDown: faSortAmountDown,
    faSortAmountDownAlt: faSortAmountDownAlt,
    faSortAmountUp: faSortAmountUp,
    faSortAmountUpAlt: faSortAmountUpAlt,
    faSortDown: faSortDown,
    faSortNumericDown: faSortNumericDown,
    faSortNumericDownAlt: faSortNumericDownAlt,
    faSortNumericUp: faSortNumericUp,
    faSortNumericUpAlt: faSortNumericUpAlt,
    faSortUp: faSortUp,
    faSpa: faSpa,
    faSpaceShuttle: faSpaceShuttle,
    faSpellCheck: faSpellCheck,
    faSpider: faSpider,
    faSpinner: faSpinner,
    faSplotch: faSplotch,
    faSprayCan: faSprayCan,
    faSquare: faSquare,
    faSquareFull: faSquareFull,
    faSquareRootAlt: faSquareRootAlt,
    faStamp: faStamp,
    faStar: faStar,
    faStarAndCrescent: faStarAndCrescent,
    faStarHalf: faStarHalf,
    faStarHalfAlt: faStarHalfAlt,
    faStarOfDavid: faStarOfDavid,
    faStarOfLife: faStarOfLife,
    faStepBackward: faStepBackward,
    faStepForward: faStepForward,
    faStethoscope: faStethoscope,
    faStickyNote: faStickyNote,
    faStop: faStop,
    faStopCircle: faStopCircle,
    faStopwatch: faStopwatch,
    faStopwatch20: faStopwatch20,
    faStore: faStore,
    faStoreAlt: faStoreAlt,
    faStoreAltSlash: faStoreAltSlash,
    faStoreSlash: faStoreSlash,
    faStream: faStream,
    faStreetView: faStreetView,
    faStrikethrough: faStrikethrough,
    faStroopwafel: faStroopwafel,
    faSubscript: faSubscript,
    faSubway: faSubway,
    faSuitcase: faSuitcase,
    faSuitcaseRolling: faSuitcaseRolling,
    faSun: faSun,
    faSuperscript: faSuperscript,
    faSurprise: faSurprise,
    faSwatchbook: faSwatchbook,
    faSwimmer: faSwimmer,
    faSwimmingPool: faSwimmingPool,
    faSynagogue: faSynagogue,
    faSync: faSync,
    faSyncAlt: faSyncAlt,
    faSyringe: faSyringe,
    faTable: faTable,
    faTableTennis: faTableTennis,
    faTablet: faTablet,
    faTabletAlt: faTabletAlt,
    faTablets: faTablets,
    faTachometerAlt: faTachometerAlt,
    faTag: faTag,
    faTags: faTags,
    faTape: faTape,
    faTasks: faTasks,
    faTaxi: faTaxi,
    faTeeth: faTeeth,
    faTeethOpen: faTeethOpen,
    faTemperatureHigh: faTemperatureHigh,
    faTemperatureLow: faTemperatureLow,
    faTenge: faTenge,
    faTerminal: faTerminal,
    faTextHeight: faTextHeight,
    faTextWidth: faTextWidth,
    faTh: faTh,
    faThLarge: faThLarge,
    faThList: faThList,
    faTheaterMasks: faTheaterMasks,
    faThermometer: faThermometer,
    faThermometerEmpty: faThermometerEmpty,
    faThermometerFull: faThermometerFull,
    faThermometerHalf: faThermometerHalf,
    faThermometerQuarter: faThermometerQuarter,
    faThermometerThreeQuarters: faThermometerThreeQuarters,
    faThumbsDown: faThumbsDown,
    faThumbsUp: faThumbsUp,
    faThumbtack: faThumbtack,
    faTicketAlt: faTicketAlt,
    faTimes: faTimes,
    faTimesCircle: faTimesCircle,
    faTint: faTint,
    faTintSlash: faTintSlash,
    faTired: faTired,
    faToggleOff: faToggleOff,
    faToggleOn: faToggleOn,
    faToilet: faToilet,
    faToiletPaper: faToiletPaper,
    faToiletPaperSlash: faToiletPaperSlash,
    faToolbox: faToolbox,
    faTools: faTools,
    faTooth: faTooth,
    faTorah: faTorah,
    faToriiGate: faToriiGate,
    faTractor: faTractor,
    faTrademark: faTrademark,
    faTrafficLight: faTrafficLight,
    faTrailer: faTrailer,
    faTrain: faTrain,
    faTram: faTram,
    faTransgender: faTransgender,
    faTransgenderAlt: faTransgenderAlt,
    faTrash: faTrash,
    faTrashAlt: faTrashAlt,
    faTrashRestore: faTrashRestore,
    faTrashRestoreAlt: faTrashRestoreAlt,
    faTree: faTree,
    faTrophy: faTrophy,
    faTruck: faTruck,
    faTruckLoading: faTruckLoading,
    faTruckMonster: faTruckMonster,
    faTruckMoving: faTruckMoving,
    faTruckPickup: faTruckPickup,
    faTshirt: faTshirt,
    faTty: faTty,
    faTv: faTv,
    faUmbrella: faUmbrella,
    faUmbrellaBeach: faUmbrellaBeach,
    faUnderline: faUnderline,
    faUndo: faUndo,
    faUndoAlt: faUndoAlt,
    faUniversalAccess: faUniversalAccess,
    faUniversity: faUniversity,
    faUnlink: faUnlink,
    faUnlock: faUnlock,
    faUnlockAlt: faUnlockAlt,
    faUpload: faUpload,
    faUser: faUser,
    faUserAlt: faUserAlt,
    faUserAltSlash: faUserAltSlash,
    faUserAstronaut: faUserAstronaut,
    faUserCheck: faUserCheck,
    faUserCircle: faUserCircle,
    faUserClock: faUserClock,
    faUserCog: faUserCog,
    faUserEdit: faUserEdit,
    faUserFriends: faUserFriends,
    faUserGraduate: faUserGraduate,
    faUserInjured: faUserInjured,
    faUserLock: faUserLock,
    faUserMd: faUserMd,
    faUserMinus: faUserMinus,
    faUserNinja: faUserNinja,
    faUserNurse: faUserNurse,
    faUserPlus: faUserPlus,
    faUserSecret: faUserSecret,
    faUserShield: faUserShield,
    faUserSlash: faUserSlash,
    faUserTag: faUserTag,
    faUserTie: faUserTie,
    faUserTimes: faUserTimes,
    faUsers: faUsers,
    faUsersCog: faUsersCog,
    faUsersSlash: faUsersSlash,
    faUtensilSpoon: faUtensilSpoon,
    faUtensils: faUtensils,
    faVectorSquare: faVectorSquare,
    faVenus: faVenus,
    faVenusDouble: faVenusDouble,
    faVenusMars: faVenusMars,
    faVest: faVest,
    faVestPatches: faVestPatches,
    faVial: faVial,
    faVials: faVials,
    faVideo: faVideo,
    faVideoSlash: faVideoSlash,
    faVihara: faVihara,
    faVirus: faVirus,
    faVirusSlash: faVirusSlash,
    faViruses: faViruses,
    faVoicemail: faVoicemail,
    faVolleyballBall: faVolleyballBall,
    faVolumeDown: faVolumeDown,
    faVolumeMute: faVolumeMute,
    faVolumeOff: faVolumeOff,
    faVolumeUp: faVolumeUp,
    faVoteYea: faVoteYea,
    faVrCardboard: faVrCardboard,
    faWalking: faWalking,
    faWallet: faWallet,
    faWarehouse: faWarehouse,
    faWater: faWater,
    faWaveSquare: faWaveSquare,
    faWeight: faWeight,
    faWeightHanging: faWeightHanging,
    faWheelchair: faWheelchair,
    faWifi: faWifi,
    faWind: faWind,
    faWindowClose: faWindowClose,
    faWindowMaximize: faWindowMaximize,
    faWindowMinimize: faWindowMinimize,
    faWindowRestore: faWindowRestore,
    faWineBottle: faWineBottle,
    faWineGlass: faWineGlass,
    faWineGlassAlt: faWineGlassAlt,
    faWonSign: faWonSign,
    faWrench: faWrench,
    faXRay: faXRay,
    faYenSign: faYenSign,
    faYinYang: faYinYang,


    fa500px: fa500px,
    faAccessibleIcon: faAccessibleIcon,
    faAccusoft: faAccusoft,
    faAcquisitionsIncorporated: faAcquisitionsIncorporated,
    faAdn: faAdn,
    faAdversal: faAdversal,
    faAffiliatetheme: faAffiliatetheme,
    faAirbnb: faAirbnb,
    faAlgolia: faAlgolia,
    faAlipay: faAlipay,
    faAmazon: faAmazon,
    faAmazonPay: faAmazonPay,
    faAmilia: faAmilia,
    faAndroid: faAndroid,
    faAngellist: faAngellist,
    faAngrycreative: faAngrycreative,
    faAngular: faAngular,
    faAppStore: faAppStore,
    faAppStoreIos: faAppStoreIos,
    faApper: faApper,
    faApple: faApple,
    faApplePay: faApplePay,
    faArtstation: faArtstation,
    faAsymmetrik: faAsymmetrik,
    faAtlassian: faAtlassian,
    faAudible: faAudible,
    faAutoprefixer: faAutoprefixer,
    faAvianex: faAvianex,
    faAviato: faAviato,
    faAws: faAws,
    faBandcamp: faBandcamp,
    faBattleNet: faBattleNet,
    faBehance: faBehance,
    faBehanceSquare: faBehanceSquare,
    faBimobject: faBimobject,
    faBitbucket: faBitbucket,
    faBitcoin: faBitcoin,
    faBity: faBity,
    faBlackTie: faBlackTie,
    faBlackberry: faBlackberry,
    faBlogger: faBlogger,
    faBloggerB: faBloggerB,
    faBluetooth: faBluetooth,
    faBluetoothB: faBluetoothB,
    faBootstrap: faBootstrap,
    faBtc: faBtc,
    faBuffer: faBuffer,
    faBuromobelexperte: faBuromobelexperte,
    faBuyNLarge: faBuyNLarge,
    faBuysellads: faBuysellads,
    faCanadianMapleLeaf: faCanadianMapleLeaf,
    faCcAmazonPay: faCcAmazonPay,
    faCcAmex: faCcAmex,
    faCcApplePay: faCcApplePay,
    faCcDinersClub: faCcDinersClub,
    faCcDiscover: faCcDiscover,
    faCcJcb: faCcJcb,
    faCcMastercard: faCcMastercard,
    faCcPaypal: faCcPaypal,
    faCcStripe: faCcStripe,
    faCcVisa: faCcVisa,
    faCentercode: faCentercode,
    faCentos: faCentos,
    faChrome: faChrome,
    faChromecast: faChromecast,
    faCloudflare: faCloudflare,
    faCloudscale: faCloudscale,
    faCloudsmith: faCloudsmith,
    faCloudversify: faCloudversify,
    faCodepen: faCodepen,
    faCodiepie: faCodiepie,
    faConfluence: faConfluence,
    faConnectdevelop: faConnectdevelop,
    faContao: faContao,
    faCottonBureau: faCottonBureau,
    faCpanel: faCpanel,
    faCreativeCommons: faCreativeCommons,
    faCreativeCommonsBy: faCreativeCommonsBy,
    faCreativeCommonsNc: faCreativeCommonsNc,
    faCreativeCommonsNcEu: faCreativeCommonsNcEu,
    faCreativeCommonsNcJp: faCreativeCommonsNcJp,
    faCreativeCommonsNd: faCreativeCommonsNd,
    faCreativeCommonsPd: faCreativeCommonsPd,
    faCreativeCommonsPdAlt: faCreativeCommonsPdAlt,
    faCreativeCommonsRemix: faCreativeCommonsRemix,
    faCreativeCommonsSa: faCreativeCommonsSa,
    faCreativeCommonsSampling: faCreativeCommonsSampling,
    faCreativeCommonsSamplingPlus: faCreativeCommonsSamplingPlus,
    faCreativeCommonsShare: faCreativeCommonsShare,
    faCreativeCommonsZero: faCreativeCommonsZero,
    faCriticalRole: faCriticalRole,
    faCss3: faCss3,
    faCss3Alt: faCss3Alt,
    faCuttlefish: faCuttlefish,
    faDAndD: faDAndD,
    faDAndDBeyond: faDAndDBeyond,
    faDailymotion: faDailymotion,
    faDashcube: faDashcube,
    faDeezer: faDeezer,
    faDelicious: faDelicious,
    faDeploydog: faDeploydog,
    faDeskpro: faDeskpro,
    faDev: faDev,
    faDeviantart: faDeviantart,
    faDhl: faDhl,
    faDiaspora: faDiaspora,
    faDigg: faDigg,
    faDigitalOcean: faDigitalOcean,
    faDiscord: faDiscord,
    faDiscourse: faDiscourse,
    faDochub: faDochub,
    faDocker: faDocker,
    faDraft2digital: faDraft2digital,
    faDribbble: faDribbble,
    faDribbbleSquare: faDribbbleSquare,
    faDropbox: faDropbox,
    faDrupal: faDrupal,
    faDyalog: faDyalog,
    faEarlybirds: faEarlybirds,
    faEbay: faEbay,
    faEdge: faEdge,
    faEdgeLegacy: faEdgeLegacy,
    faElementor: faElementor,
    faEllo: faEllo,
    faEmber: faEmber,
    faEmpire: faEmpire,
    faEnvira: faEnvira,
    faErlang: faErlang,
    faEthereum: faEthereum,
    faEtsy: faEtsy,
    faEvernote: faEvernote,
    faExpeditedssl: faExpeditedssl,
    faFacebook: faFacebook,
    faFacebookF: faFacebookF,
    faFacebookMessenger: faFacebookMessenger,
    faFacebookSquare: faFacebookSquare,
    faFantasyFlightGames: faFantasyFlightGames,
    faFedex: faFedex,
    faFedora: faFedora,
    faFigma: faFigma,
    faFirefox: faFirefox,
    faFirefoxBrowser: faFirefoxBrowser,
    faFirstOrder: faFirstOrder,
    faFirstOrderAlt: faFirstOrderAlt,
    faFirstdraft: faFirstdraft,
    faFlickr: faFlickr,
    faFlipboard: faFlipboard,
    faFly: faFly,
    faFontAwesome: faFontAwesome,
    faFontAwesomeAlt: faFontAwesomeAlt,
    faFontAwesomeFlag: faFontAwesomeFlag,
    faFontAwesomeLogoFull: faFontAwesomeLogoFull,
    faFonticons: faFonticons,
    faFonticonsFi: faFonticonsFi,
    faFortAwesome: faFortAwesome,
    faFortAwesomeAlt: faFortAwesomeAlt,
    faForumbee: faForumbee,
    faFoursquare: faFoursquare,
    faFreeCodeCamp: faFreeCodeCamp,
    faFreebsd: faFreebsd,
    faFulcrum: faFulcrum,
    faGalacticRepublic: faGalacticRepublic,
    faGalacticSenate: faGalacticSenate,
    faGetPocket: faGetPocket,
    faGg: faGg,
    faGgCircle: faGgCircle,
    faGit: faGit,
    faGitAlt: faGitAlt,
    faGitSquare: faGitSquare,
    faGithub: faGithub,
    faGithubAlt: faGithubAlt,
    faGithubSquare: faGithubSquare,
    faGitkraken: faGitkraken,
    faGitlab: faGitlab,
    faGitter: faGitter,
    faGlide: faGlide,
    faGlideG: faGlideG,
    faGofore: faGofore,
    faGoodreads: faGoodreads,
    faGoodreadsG: faGoodreadsG,
    faGoogle: faGoogle,
    faGoogleDrive: faGoogleDrive,
    faGooglePay: faGooglePay,
    faGooglePlay: faGooglePlay,
    faGooglePlus: faGooglePlus,
    faGooglePlusG: faGooglePlusG,
    faGooglePlusSquare: faGooglePlusSquare,
    faGoogleWallet: faGoogleWallet,
    faGratipay: faGratipay,
    faGrav: faGrav,
    faGripfire: faGripfire,
    faGrunt: faGrunt,
    faGuilded: faGuilded,
    faGulp: faGulp,
    faHackerNews: faHackerNews,
    faHackerNewsSquare: faHackerNewsSquare,
    faHackerrank: faHackerrank,
    faHips: faHips,
    faHireAHelper: faHireAHelper,
    faHive: faHive,
    faHooli: faHooli,
    faHornbill: faHornbill,
    faHotjar: faHotjar,
    faHouzz: faHouzz,
    faHtml5: faHtml5,
    faHubspot: faHubspot,
    faIdeal: faIdeal,
    faImdb: faImdb,
    faInnosoft: faInnosoft,
    faInstagram: faInstagram,
    faInstagramSquare: faInstagramSquare,
    faInstalod: faInstalod,
    faIntercom: faIntercom,
    faInternetExplorer: faInternetExplorer,
    faInvision: faInvision,
    faIoxhost: faIoxhost,
    faItchIo: faItchIo,
    faItunes: faItunes,
    faItunesNote: faItunesNote,
    faJava: faJava,
    faJediOrder: faJediOrder,
    faJenkins: faJenkins,
    faJira: faJira,
    faJoget: faJoget,
    faJoomla: faJoomla,
    faJs: faJs,
    faJsSquare: faJsSquare,
    faJsfiddle: faJsfiddle,
    faKaggle: faKaggle,
    faKeybase: faKeybase,
    faKeycdn: faKeycdn,
    faKickstarter: faKickstarter,
    faKickstarterK: faKickstarterK,
    faKorvue: faKorvue,
    faLaravel: faLaravel,
    faLastfm: faLastfm,
    faLastfmSquare: faLastfmSquare,
    faLeanpub: faLeanpub,
    faLess: faLess,
    faLine: faLine,
    faLinkedin: faLinkedin,
    faLinkedinIn: faLinkedinIn,
    faLinode: faLinode,
    faLinux: faLinux,
    faLyft: faLyft,
    faMagento: faMagento,
    faMailchimp: faMailchimp,
    faMandalorian: faMandalorian,
    faMarkdown: faMarkdown,
    faMastodon: faMastodon,
    faMaxcdn: faMaxcdn,
    faMdb: faMdb,
    faMedapps: faMedapps,
    faMedium: faMedium,
    faMediumM: faMediumM,
    faMedrt: faMedrt,
    faMeetup: faMeetup,
    faMegaport: faMegaport,
    faMendeley: faMendeley,
    faMicroblog: faMicroblog,
    faMicrosoft: faMicrosoft,
    faMix: faMix,
    faMixcloud: faMixcloud,
    faMixer: faMixer,
    faMizuni: faMizuni,
    faModx: faModx,
    faMonero: faMonero,
    faNapster: faNapster,
    faNeos: faNeos,
    faNimblr: faNimblr,
    faNode: faNode,
    faNodeJs: faNodeJs,
    faNpm: faNpm,
    faNs8: faNs8,
    faNutritionix: faNutritionix,
    faOctopusDeploy: faOctopusDeploy,
    faOdnoklassniki: faOdnoklassniki,
    faOdnoklassnikiSquare: faOdnoklassnikiSquare,
    faOldRepublic: faOldRepublic,
    faOpencart: faOpencart,
    faOpenid: faOpenid,
    faOpera: faOpera,
    faOptinMonster: faOptinMonster,
    faOrcid: faOrcid,
    faOsi: faOsi,
    faPage4: faPage4,
    faPagelines: faPagelines,
    faPalfed: faPalfed,
    faPatreon: faPatreon,
    faPaypal: faPaypal,
    faPennyArcade: faPennyArcade,
    faPerbyte: faPerbyte,
    faPeriscope: faPeriscope,
    faPhabricator: faPhabricator,
    faPhoenixFramework: faPhoenixFramework,
    faPhoenixSquadron: faPhoenixSquadron,
    faPhp: faPhp,
    faPiedPiper: faPiedPiper,
    faPiedPiperAlt: faPiedPiperAlt,
    faPiedPiperHat: faPiedPiperHat,
    faPiedPiperPp: faPiedPiperPp,
    faPiedPiperSquare: faPiedPiperSquare,
    faPinterest: faPinterest,
    faPinterestP: faPinterestP,
    faPinterestSquare: faPinterestSquare,
    faPlaystation: faPlaystation,
    faProductHunt: faProductHunt,
    faPushed: faPushed,
    faPython: faPython,
    faQq: faQq,
    faQuinscape: faQuinscape,
    faQuora: faQuora,
    faRProject: faRProject,
    faRaspberryPi: faRaspberryPi,
    faRavelry: faRavelry,
    faReact: faReact,
    faReacteurope: faReacteurope,
    faReadme: faReadme,
    faRebel: faRebel,
    faRedRiver: faRedRiver,
    faReddit: faReddit,
    faRedditAlien: faRedditAlien,
    faRedditSquare: faRedditSquare,
    faRedhat: faRedhat,
    faRenren: faRenren,
    faReplyd: faReplyd,
    faResearchgate: faResearchgate,
    faResolving: faResolving,
    faRev: faRev,
    faRocketchat: faRocketchat,
    faRockrms: faRockrms,
    faRust: faRust,
    faSafari: faSafari,
    faSalesforce: faSalesforce,
    faSass: faSass,
    faSchlix: faSchlix,
    faScribd: faScribd,
    faSearchengin: faSearchengin,
    faSellcast: faSellcast,
    faSellsy: faSellsy,
    faServicestack: faServicestack,
    faShirtsinbulk: faShirtsinbulk,
    faShopify: faShopify,
    faShopware: faShopware,
    faSimplybuilt: faSimplybuilt,
    faSistrix: faSistrix,
    faSith: faSith,
    faSketch: faSketch,
    faSkyatlas: faSkyatlas,
    faSkype: faSkype,
    faSlack: faSlack,
    faSlackHash: faSlackHash,
    faSlideshare: faSlideshare,
    faSnapchat: faSnapchat,
    faSnapchatGhost: faSnapchatGhost,
    faSnapchatSquare: faSnapchatSquare,
    faSoundcloud: faSoundcloud,
    faSourcetree: faSourcetree,
    faSpeakap: faSpeakap,
    faSpeakerDeck: faSpeakerDeck,
    faSpotify: faSpotify,
    faSquarespace: faSquarespace,
    faStackExchange: faStackExchange,
    faStackOverflow: faStackOverflow,
    faStackpath: faStackpath,
    faStaylinked: faStaylinked,
    faSteam: faSteam,
    faSteamSquare: faSteamSquare,
    faSteamSymbol: faSteamSymbol,
    faStickerMule: faStickerMule,
    faStrava: faStrava,
    faStripe: faStripe,
    faStripeS: faStripeS,
    faStudiovinari: faStudiovinari,
    faStumbleupon: faStumbleupon,
    faStumbleuponCircle: faStumbleuponCircle,
    faSuperpowers: faSuperpowers,
    faSupple: faSupple,
    faSuse: faSuse,
    faSwift: faSwift,
    faSymfony: faSymfony,
    faTeamspeak: faTeamspeak,
    faTelegram: faTelegram,
    faTelegramPlane: faTelegramPlane,
    faTencentWeibo: faTencentWeibo,
    faTheRedYeti: faTheRedYeti,
    faThemeco: faThemeco,
    faThemeisle: faThemeisle,
    faThinkPeaks: faThinkPeaks,
    faTiktok: faTiktok,
    faTradeFederation: faTradeFederation,
    faTrello: faTrello,
    faTripadvisor: faTripadvisor,
    faTumblr: faTumblr,
    faTumblrSquare: faTumblrSquare,
    faTwitch: faTwitch,
    faTwitter: faTwitter,
    faTwitterSquare: faTwitterSquare,
    faTypo3: faTypo3,
    faUber: faUber,
    faUbuntu: faUbuntu,
    faUikit: faUikit,
    faUmbraco: faUmbraco,
    faUncharted: faUncharted,
    faUniregistry: faUniregistry,
    faUnity: faUnity,
    faUnsplash: faUnsplash,
    faUntappd: faUntappd,
    faUps: faUps,
    faUsb: faUsb,
    faUsps: faUsps,
    faUssunnah: faUssunnah,
    faVaadin: faVaadin,
    faViacoin: faViacoin,
    faViadeo: faViadeo,
    faViadeoSquare: faViadeoSquare,
    faViber: faViber,
    faVimeo: faVimeo,
    faVimeoSquare: faVimeoSquare,
    faVimeoV: faVimeoV,
    faVine: faVine,
    faVk: faVk,
    faVnv: faVnv,
    faVuejs: faVuejs,
    faWatchmanMonitoring: faWatchmanMonitoring,
    faWaze: faWaze,
    faWeebly: faWeebly,
    faWeibo: faWeibo,
    faWeixin: faWeixin,
    faWhatsapp: faWhatsapp,
    faWhatsappSquare: faWhatsappSquare,
    faWhmcs: faWhmcs,
    faWikipediaW: faWikipediaW,
    faWindows: faWindows,
    faWix: faWix,
    faWizardsOfTheCoast: faWizardsOfTheCoast,
    faWodu: faWodu,
    faWolfPackBattalion: faWolfPackBattalion,
    faWordpress: faWordpress,
    faWordpressSimple: faWordpressSimple,
    faWpbeginner: faWpbeginner,
    faWpexplorer: faWpexplorer,
    faWpforms: faWpforms,
    faWpressr: faWpressr,
    faXbox: faXbox,
    faXing: faXing,
    faXingSquare: faXingSquare,
    faYCombinator: faYCombinator,
    faYahoo: faYahoo,
    faYammer: faYammer,
    faYandex: faYandex,
    faYandexInternational: faYandexInternational,
    faYarn: faYarn,
    faYelp: faYelp,
    faYoast: faYoast,
    faYoutube: faYoutube,
    faYoutubeSquare: faYoutubeSquare,
    faZhihu: faZhihu

}
